### ISSUE TITLE
Something wrong at the boundary 7300KHz SSB

### ISSUE THREAD

**Issue by den3rats** [diqezit/ats20_ats_ex#13]
Sequense is:
- Switch to SSB (LSB) mode;
- Set step = 500 Hz;
- set up the 41m band using "band+" button. Current frequency = 7300 KHz, band = 41m, OK;
- Do manual step down. Current frequency = 7299 KHz, band = 41m (wrong combination);
- Do manual step down again. It suddenly jumps to 7000 KHz (why?), band = 40m;

**Comment by diqezit** [comment]
Hi. Thank you, this problem has been solved by 4.10

**Comment by den3rats** [comment]
Hi!
It got better, but not perfect:

- Switch to SSB (LSB) mode;
- Set step = 500 Hz;
- Set up the 41m band using "band+" button. Current frequency = 7300 KHz, band = 41m, OK;
- Do manual step down. Current frequency = 7299 KHz, band = 41m, NOK 
   Still wrong combination. 7300 KHz and 40m expected, as in next step ↓;
- Do manual step down again. Current frequency = 7300 KHz, band = 40m, OK .
- Do manual step down again. Current frequency = 7299 KHz, band = 40m, OK .

**Comment by diqezit** [comment]
Hi. Just wanted to let you know that I took your recommendation. And have made the corrections in the new version. If you have a chance let me know the results and we can close the Issue

**Comment by den3rats** [comment]
Hi!
Sorry, inspiration and energy have left me for a week.
I tested several ideas in this project, but overestimated my skills and got no results.

OK there.
